FROM cpp-web-dev:build-1.0.0 as builder
COPY src/ /src/
WORKDIR /build
RUN cmake /src && cmake --build .
FROM cpp-web-dev:lean-1.0.0
WORKDIR /app
COPY --from=builder /build/cpp-web-app .
CMD ["./cpp-web-app"]